packaging_format = 2

id = "kiwix"
name = "Kiwix"
description.en = "Sharing Web content with people without Internet access"
description.fr = "Partager du contenu Web avec des personnes sans accès à Internet"

version = "3.5.0~ynh4"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.kiwix.org/"
demo = "http://library.kiwix.org/"
admindoc = "https://wiki.kiwix.org/wiki/Kiwix-serve/"
code = "https://github.com/kiwix/kiwix-tools"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        amd64.url = "https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64-3.5.0.tar.gz"
        amd64.sha256 = "110d4b00b0c6aa3fa6982c3f3cc5d4143af90caa935b1e23e0ecd80680f269e8"
        armhf.url = "https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armhf-3.5.0.tar.gz"
        armhf.sha256 = "41242099546401250268fee9bf48c43c2217b0a1d14efb1b90ae15bafcf05bcc"
        arm64.url = "https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-aarch64-3.5.0.tar.gz"
        arm64.sha256 = "2a5c88bba79ff8b253138bbd960c40c0588a13a9e52b6a41cd979c0940f7d72c"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
